config/routes.rb
Rails.application.routes.draw do

  resources :offers do
    member do
      get 'accept'
      get 'decline'
      get 'payment'
      get 'express_checkout'
    end
  end
  resources :login, only: [:index]
  resources :search, only: [:index]
	resources :listings do
    member do
      get 'offer'
      post 'favourite'
      post 'unfavourite'
    end
  end

  get '/brands/featured', to: 'brands#featured'
	resources :brands
  resources :category

	devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => 
    "users/omniauth_callbacks" }
  root to: 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord

  # allow filterable trait
  include Filterable

	# setup friendly id
	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

  belongs_to :user
	belongs_to :brand
	belongs_to :category

  has_many :listing_images, dependent: :destroy
  has_many :offers
  has_many :wishlists
	
	# taggable
	acts_as_taggable_on :colours

  # validation
  validates_presence_of :title, :description, :price

  # scopes
  scope :category, -> (category) { where category: category.split('-') }
  scope :brand, -> (brand) { where brand: brand.split('-') }
  scope :colour, -> (colour) { joins(:taggings).where(:taggings => { :tag_id => colour.split('-') } ) }
  scope :minPrice, -> (minPrice) { where 'price >= ?', minPrice }
  scope :maxPrice, -> (maxPrice) { where 'price <= ?', maxPrice }

	def slug_candidates
		[
      :title,
      [:id, :title],
      [:id, :title, :user_id]
		]
	end

	def first_image
		self.listing_images.first ? self.listing_images.first.image.url : "https://placeholdit.co//i/315x315"
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy, :offer, :favourite, :unfavourite]
	before_action :set_dependents
  before_action :set_wishlist, only: [:index, :show]
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_listing_information, only: [:index]
  skip_before_action :verify_authenticity_token, only: [:favourite, :unfavourite]

  # GET /listings
  # GET /listings.json
  def index

    @brands = Brand.order(:name)
    @categories = Category.order(:name)
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # GET /listings/1/offer
  def offer
    @offer = Offer.new
    @offer.listing = @listing

    respond_to do |format|
      format.html { render :template => "listings/offer" }
    end
  end
  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    @listing.completed = 0

    respond_to do |format|
      if @listing.save
        if params[:images] 
          params[:images].each do |img|
            @listing.listing_images.create(:image => img)
          end
        end
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        if params[:images]
          params[:images].each do |img|
            @listing.listing_images.create(:image => img)
          end
        end
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /listings/1/favourite
  def favourite
    wishlist = Wishlist.new
    wishlist.listing = @listing
    wishlist.user = current_user

    respond_to do |format|
      if wishlist.save
        format.json { render json: wishlist, status: :ok }
      else
        format.json { render json: "error", status: :unprocessable_entity } 
      end
    end
  end

  # DELETE /listings/1/unfavourite
  def unfavourite
    wishlist = @listing.wishlists.where(:user => current_user).first or not_found
  
    wishlist.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
			@listing = Listing.friendly.find(params[:id])
    end

		# get all brands and categories when creating a new listing
		def set_dependents
			@brands = Brand.all.order('name')
			@categories = Category.all.order('name')
		end
    
    def set_listing_information
      @maximum_price = Listing.maximum(:price)
      @minimum_price = Listing.minimum(:price)
      @q = Listing.ransack(params[:q])
      @listings = @q.result.filter(params.slice(:brand, :category, :colour, :minPrice, :maxPrice))
        .order(created_at: :desc)
        .paginate(:page => params[:page], :per_page => 32)
    end

    def set_wishlist
      if user_signed_in?
        @wishlists = current_user.wishlists.pluck(:listing_id)
      else
        @wishlists = []
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:category_id, :brand_id, :title, :description, :price, :colour_list)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, html: { multipart: true, :class => 'login-form' }, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
		<%= form.collection_select :brand_id, @brands, :id, :name, class: 'form-control' %>
  </div>

	<div class="field">
		<%= form.label :category %>
		<%= form.collection_select :category_id, @categories, :id, :name, class: 'form-control' %>
	</div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :listing_title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :listing_price, class: 'form-control' %>
  </div>

	<div class="field">
		<%= form.label :colour_list %>
		<%= form.text_field :colour_list, id: :listing_colour_list, class: 'form-control' %>
	</div>

  <%= file_field_tag "images[]", type: :file, multiple: true, class: 'form-control' %>

  <div class="actions">
    <%= form.submit class: 'btn btn-success btn-ghost' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<section class="container-fluid padding-top-3x">
				<h1 class="space-top-half tablet-center">All Listings</h1>
</section>

<section class="container-fluid padding-bottom-3x">

<%= render 'listings/partials/filters_and_listings' %>

app/views/listings/new.html.erb
<section class="container"
		<div class="row">
				<div class="col-md-12 col-sm-12">
						<h1>Add a new listing</h1>
				</div>
				<div class="col-md-12 col-sm-12">
						<%= render 'form', listing: @listing %>

						<%= link_to 'Back', listings_path %>
				</div>
		</div>
</section>

app/views/listings/offer.html.erb
<section class="container">
	<div class="row">
			<h1>Making an offer for <%= link_to @offer.listing.title, @offer.listing %></h1>
		<div class="col-md-3 col-sm-4">
			<%= render 'offers/form', offer: @offer %>
		</div>
		<div class="col-mad-offset-1 col-sm-8">
			<a href="<%= listings_url + "/" + @offer.listing.slug %>"><%= image_tag @offer.listing.first_image, height: 541, width: 600 %></a>
		</div>
	</div>
</section>

app/views/listings/show.html.erb
<!-- Pager + Product Gallery -->
<section class="fw-section bg-gray padding-top-3x">
  <div class="container padding-top">
		<p id="notice" class="text-success"><%= notice %></p>
    <!-- Product Gallery -->
    <div class="product-gallery">
      <!-- Preview -->
      <ul class="product-gallery-preview">
        <% @listing.listing_images.each_with_index do |image, i| %>
          <li <% if i == 0 %>class="current"<% end %> id="preview<%= image.id %>"><%= image_tag image.image.url, height: 541, width: 600 %></li>
        <% end %>
      </ul><!-- .product-gallery-preview -->
      <!-- Thumblist -->
      <ul class="product-gallery-thumblist">
        <% @listing.listing_images.each_with_index do |image, i| %>
          <li <% if i == 0 %>class="active"<% end %>><a href="#preview<%= image.id %>">
            <%= image_tag image.image.url(:thumbnail) %>
          </a></li>
        <% end %>
      </ul><!-- .product-gallery-thumblist -->
    </div><!-- .product-gallery -->
  </div><!-- .container -->
</section><!-- .fw-section.bg-gray -->

<!-- Product Info -->
<section class="fw-section bg-gray padding-bottom-3x">
  <div class="container">
    <div class="product-info padding-top-2x text-center">
      <h1 class="h2 space-bottom-half"><%= @listing.title %></h1>
      <h2>$<%= @listing.price %></h2>
      <p class="text-sm text-gray"><%= @listing.description %></p>
      <div class="product-meta">
        <div class="product-category">
          <strong>Category: </strong>
          <%= link_to @listing.category.name, @listing.category %>
        </div>
      </div><!-- .product-meta -->
      <div class="product-tools shop-item">
        <a href="<%= offer_listing_path @listing %>" class="add-to-cart">
          <em>Make an offer</em>
          <svg x="0px" y="0px" width="32px" height="32px" viewBox="0 0 32 32">
            <path stroke-dasharray="19.79 19.79" stroke-dashoffset="19.79" fill="none" stroke="#FFFFFF" stroke-width="2" stroke-linecap="square" stroke-miterlimit="10" d="M9,17l3.9,3.9c0.1,0.1,0.2,0.1,0.3,0L23,11"></path>
          </svg>
        </a><!-- .add-to-cart -->
      </div><!-- .product-tools -->
    </div><!-- .product-info -->
  </div><!-- .container -->
</section><!-- .fw-section.bg-gray -->

<!-- Product Tabs -->
<section class="container padding-top-2x">
  <!-- Nav Tabs -->
  <ul class="nav-tabs text-center" role="tablist">
    <li class="active"><a href="#description" role="tab" data-toggle="tab">Description</a></li>
    <li><a href="#additional" role="tab" data-toggle="tab">Additional Info</a></li>
  </ul><!-- .nav-tabs -->
  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane transition fade in active" id="description">
      <div class="row space-top">
        <div class="col-md-12">
          <p><%= @listing.description %></p>
        </div>
      </div>
    </div><!-- .tab-pane -->
    <div role="tabpanel" class="tab-pane transition fade" id="additional">
      <div class="row space-top">
        <div class="col-md-6">
          <table class="table-no-border">
            <tr>
              <th>Weight</th>
              <td>2.65 kg</td>
            </tr>
            <tr>
              <th>Dimensions</th>
              <td>120 x 75 x 90 cm</td>
            </tr>
            <tr>
              <th>Materials</th>
              <td>40% wood, 37% cotton, 23% plastic</td>
            </tr>
          </table>
        </div>
        <div class="col-md-6">
          <table class="table-no-border">
            <tr>
              <th>Colors</th>
              <td>Blue, Creme, Orange, Red</td>
            </tr>
            <tr>
              <th>Manufacturer</th>
              <td>Norway</td>
            </tr>
            <tr>
              <th>Other Info</th>
              <td>Repellendus ea laudantium pariatur eum.</td>
            </tr>
          </table>
        </div>
      </div>
    </div><!-- .tab-pane -->
  </div><!-- .tab-content -->
</section><!-- .container -->