config/routes.rb
Rails.application.routes.draw do

  resources :offers do
    member do
      get 'accept'
      get 'decline'
      get 'payment'
      get 'express_checkout'
    end
  end
  resources :login, only: [:index]
  resources :search, only: [:index]
	resources :listings do
    member do
      get 'offer'
      post 'favourite'
      post 'unfavourite'
    end
  end

  get '/brands/featured', to: 'brands#featured'
	resources :brands
  resources :category

	devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => 
    "users/omniauth_callbacks" }
  root to: 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<footer class="footer space-top-2x">
      <div class="column">
        <p class="text-sm">Need support? Call <span class="text-primary">+61420000000 </span></p>
        <div class="social-bar text-center space-bottom">
          <a href="#" class="sb-skype" data-toggle="tooltip" data-placement="top" title="Skype">
            <i class="socicon-skype"></i>
          </a>
          <a href="#" class="sb-facebook" data-toggle="tooltip" data-placement="top" title="Facebook">
            <i class="socicon-facebook"></i>
          </a>
          <a href="#" class="sb-google-plus" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google+">
            <i class="socicon-googleplus"></i>
          </a>
          <a href="#" class="sb-twitter" data-toggle="tooltip" data-placement="top" title="Twitter">
            <i class="socicon-twitter"></i>
          </a>
          <a href="#" class="sb-instagram" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
            <i class="socicon-instagram"></i>
          </a>
        </div><!-- .social-bar -->
        <p class="copyright">&copy; 2017. Made with <i class="text-danger material-icons favorite"></i> by lachlan.</p>
      </div><!-- .column -->
      <div class="column">
        <h3 class="widget-title">
          Subscription
          <small>To receive latest offers and discounts from the shop.</small>
        </h3>
        <form action="" method="post" target="_blank" class="subscribe-form" novalidate>
          <input type="email" class="form-control" name="EMAIL" placeholder="Your e-mail">
          <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
          <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c7103e2c981361a6639545bd5_1194bb7544" tabindex="-1" value=""></div>
          <button type="submit"><i class="material-icons send"></i></button>
        </form>
      </div><!-- .column -->
      <div class="column">
        <h3 class="widget-title">
          Payment Methods
          <small>We support one of the following payment methods.</small>
        </h3>
        <div class="cards"><img src="img/cards.png" alt="Cards"></div>
        <!-- Scroll To Top Button -->
        <div class="scroll-to-top-btn"><i class="material-icons trending_flat"></i></div>
      </div><!-- .column -->
    </footer><!-- .footer -->

app/views/partials/_navigation.html.erb
<header class="navbar navbar-sticky">
	<!-- Site Logo -->
	<a href="<%= root_path %>" class="site-logo visible-desktop">
		<span>[</span> HUNTER <span>]</span>
	</a><!-- site-logo.visible-desktop -->
	<a href="<%= root_path %>" class="site-logo visible-mobile">
		<span>[</span> HUNTER <span>]</span>
	</a><!-- site-logo.visible-mobile -->

	<!-- Main Navigation -->
	<!-- Control the position of navigation via modifier classes: "text-left, text-center, text-right" -->
	<nav class="main-navigation text-center">
		<ul class="menu">
			<li><%= link_to "Add a Listing", new_listing_path %></li>
			<li><%= link_to "Designers", brands_featured_path %></li>
			<li><%= link_to "All Listings", listings_path %></li>
			<li><%= link_to "Categories", category_index_path %></li>
			<% if user_signed_in? %>
        <li><%= link_to "Offers", offers_path %></li>
      <% end %>
		</ul><!-- .menu -->
	</nav><!-- .main-navigation -->
	<div class="toolbar">
		<div class='inner'>
			<a class="mobile-menu-toggle"><i class="material-icons menu"></i></a>
			<% if user_signed_in? %>
					<%= link_to edit_user_registration_path do %>
						<i class="material-icons person"></i>
					<% end %>
					<%= link_to('Logout', destroy_user_session_path, method: :delete) %>   
			<% else %>
				<%= link_to login_index_path do %>
						<i class="material-icons person"></i>
				<% end %>
			<% end %>
		</div>
	</div><!-- .toolbar -->
</header>