config/routes.rb
Rails.application.routes.draw do

  resources :offers do
    member do
      get 'accept'
      get 'decline'
      get 'payment'
      get 'express_checkout'
    end
  end
  resources :login, only: [:index]
  resources :search, only: [:index]
	resources :listings do
    member do
      get 'offer'
      post 'favourite'
      post 'unfavourite'
    end
  end

  get '/brands/featured', to: 'brands#featured'
	resources :brands
  resources :category

	devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => 
    "users/omniauth_callbacks" }
  root to: 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :listing
  belongs_to :user

  validates_presence_of :price

  def print_stage
    case stage
      when 0
        "Offer Declined"
      when 1
        "Pending"
      when 2
        "Awaiting Payment"
      when 3
        "Payment Received"
    end
  end

  def purchase 
    response = EXPRESS_GATEWAY.purchase(price*100, express_purchase_options)
    response.success?
  end

  def stage_class
    case stage
      when 0
        "text-danger"
      when 1
      when 2
        "text-warning"
      when 3
        "text-success"
    end
  end

  def express_token=(token)
    self[:express_token] = token
    if !token.blank?
      # you can dump details var if you need more info from buyer
      details = EXPRESS_GATEWAY.details_for(token)
      self.express_payer_id = details.payer_id
    end
  end

  private

  def express_purchase_options
    {
      :ip => ip,
      :currency => "AUD",
      :token => express_token,
      :payer_id => express_payer_id
    }
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy, :accept, :decline, :payment, :express_checkout]
  before_action :authenticate_user!

  # GET /offers
  # GET /offers.json
  def index
    @active_offers = current_user.offers.where("stage NOT IN (0, 3)")
    @completed_offers = current_user.offers.where("stage IN (0, 3)")

    @active_listings = Offer.joins(:listing).where("listings.user_id" => current_user.id)
      .where("listings.completed = false AND offers.stage NOT IN (0, 3)")
    @completed_listings = Offer.joins(:listing).where("listings.user_id" => current_user.id)
      .where("listings.completed = true and offers.stage = 3") 

    @wishlists = Listing.joins(:wishlists).where("wishlists.user_id" => current_user.id)
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.user_id = current_user.id
    @offer.stage = 1

    respond_to do |format|
      if @offer.save
				format.html { redirect_to @offer.listing, notice: 'Please wait for an email from the seller to see whether you were successful!' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /offers/1/accept
  def accept
    @listing = @offer.listing
    unless @listing.user_id == current_user.id
      format.html { redirect_to @offer, alert: 'You do not have permission to accept this offer!' } 
    end

    @offer.stage = 2
    
    respond_to do |format|
      if @offer.save
        format.html { redirect_to offers_url, notice: 'Offer was accepted!.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :index }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /offers/1/decline
  def decline
    @listing = @offer.listing
    unless @listing.user_id == current_user.id
      format.html { redirect_to @offer, alert: 'You do not have permission to decline this offer!' } 
    end

    @offer.stage = 0
    
    respond_to do |format|
      if @offer.save
        format.html { redirect_to offers_url, notice: 'Offer was declined!.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :index }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def express_checkout
    response = EXPRESS_GATEWAY.setup_purchase(@offer.price*100,
      ip: request.remote_ip,
      return_url: payment_offer_url(@offer),
      cancel_return_url: offers_url,
      currency: "AUD",
      allow_guest_checkout: false,
      items: [{name: @offer.listing.title, description: @offer.listing.description, quantity: "1", amount: @offer.price*100}]
    )
    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end
  
  # GET /offers/1/payment
  def payment
    @listing = @offer.listing

    unless @offer.user_id == current_user.id
      format.html { redirect_to @offer, alert: 'To do not have permission to make payment for this listing!' }
    end

    # TODO: do paypal stuff here
    @offer.stage = 3
    @listing.completed = 1 
    @listing.save
    @offer.ip = request.remote_ip
    @offer.express_token = params[:token]
    if @offer.save
      if @offer.purchase  
        redirect_to offers_url @offer
      end
    else 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:listing_id, :price)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_with(model: offer, local: true) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :listing_id, id: :offer_listing_id, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :offer_price, placeholder: offer.listing.price %>
  </div>

  <div class="actions">
    <%= form.submit "Make an offer", class: "btn btn-success btn-ghost" %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Content -->
<section class="container padding-top-3x">
  <h1 class="mobile-center">Hey, <span class="text-semibold"><%= current_user.name %></span></h1>
  <div class="row padding-top">
    <div class="col-sm-12 padding-bottom-3x">
      <!-- Nav Tabs -->
      <ul class="nav-tabs mobile-center" role="tablist">
        <li class='active'><a href="#active" role="tab" data-toggle="tab">
          <i class="material-icons shopping_basket"></i>
          Active Offers (<%= @active_offers.count %>)
        </a></li>
        <li><a href='#completed' role='tab' data-toggle="tab">
          <i class="material-icons receipt"></i> 
          Completed Offers (<%= @completed_offers.count %>)
        </a></li>
        <li><a href='#activelistings' role='tab' data-toggle="tab">
          <i class="material-icons store"></i>
          Active Listings (<%= @active_listings.count %>)
        </a></li>
        <li><a href='#completedlistings' role="tab" data-toggle="tab">
          <i class="material-icons done"></i>
          Completed Listings (<%= @completed_listings.count %>)
        </a></li>
        <li><a href="#wishlist" role="tab" data-toggle="tab">
          <i class="material-icons favorite"></i>
          Wishlist (<%= @wishlists.count %>)
        </a></li>
      </ul><!-- .nav-tabs -->

      <!-- Tab Panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane transition fade scale in active" id="active">
          <div class="table-responsive">
            <table>
              <thead>
                <tr>
                  <th></th>
                  <th>Listing</th>
                  <th>Date Offered</th>
                  <th>Price</th>
                  <th>Status</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @active_offers.each do |offer| %>
                  <tr>
                    <td><%= image_tag offer.listing.first_image, height: 40, width: 40 %>
                    <td><%= link_to offer.listing.title, offer %></td>
                    <td><%= offer.created_at %></td>
                    <td><%= offer.price %></td>
                    <td><span class='<%= offer.stage_class %>'><%= offer.print_stage %></span></td>
                    <td>
                      <% if offer.stage == 2 %>
                        <%= link_to 'Make Payment', express_checkout_offer_path(offer), class: 'btn btn-sm btn-success' %>
                      <% end %>
                      <% unless offer.stage == 3 %>
                        <%= link_to 'Remove Offer', offer,  method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div><!-- .tab-pane#active -->
        <div role="tabpanel" class="tab-pane transition fade scale in" id="completed">
          <div class="table-responsive">
            <table>
              <thead>
                <tr>
                  <th></th>
                  <th>Listing</th>
                  <th>Date Offered</th>
                  <th>Price</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <% @completed_offers.each do |offer| %>
                  <tr>
                    <td><%= image_tag offer.listing.first_image %>
                    <td><%= link_to offer.listing.title, offer %></td>
                    <td><%= offer.created_at %></td>
                    <td><%= offer.price %></td>
                    <td><span class='<%= offer.stage_class %>'><%= offer.print_stage%></span></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div><!-- .tab-pane# -->
        <div role="tabpanel" class="tab-pane transition fade scale in" id="activelistings">
          <div class="table-responsive">
            <table>
              <thead>
                <tr>
                  <th></th>
                  <th>Listing</th>
                  <th>Date Offered</th>
                  <th>Price</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <% @active_listings.each do |offer| %>
                  <tr>
                    <td><%= image_tag offer.listing.first_image %>
                    <td><%= link_to offer.listing.title, offer %></td>
                    <td><%= offer.created_at %></td>
                    <td><%= offer.price %></td>
                    <td>
                      <% if offer.stage == 1 %>
                        <%= link_to "Accept Offer", accept_offer_path(offer), class: 'btn btn-sm btn-success' %>
                        <%= link_to "Decline Offer", decline_offer_path(offer), class: 'btn btn-sm btn-danger' %>
                      <% else %>
                        <span class='<%= offer.stage_class %>'><%= offer.print_stage %></span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div><!-- .tab-pane# -->
        <div role="tabpanel" class="tab-pane transition fade scale in" id="completedlistings">
          <div class="table-responsive">
            <table>
              <thead>
                <tr>
                  <th></th>
                  <th>Listing</th>
                  <th>Date Offered</th>
                  <th>Price</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <% @completed_listings.each do |offer| %>
                  <tr>
                    <td><%= image_tag offer.listing.first_image %>
                    <td><%= link_to offer.listing.title, offer %></td>
                    <td><%= offer.created_at %></td>
                    <td><%= offer.price %></td>
                    <td>
                      <% if offer.stage == 1 %>
                        <%= link_to "Accept Offer", accept_offer_path(offer), class: 'btn btn-sm btn-success' %>
                        <%= link_to "Decline Offer", decline_offer_path(offer), class: 'btn btn-sm btn-danger' %>
                      <% else %>
                        <span class='<%= offer.stage_class %>'><%= offer.print_stage %></span>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div><!-- .tab-pane# -->
        <div role="tabpanel" class="tab-pane transition fade scale" id="wishlist">
          <div class="table-responsive">
            <table>
              <thead>
                <tr>
                  <th>Listing</th>
                  <th>Price</th>
                </tr>
              </thead>
              <tbody>
                <% @wishlists.each do |listing| %>
                  <tr>
                    <td><%= link_to listing.title, listing %></td>
                    <td><%= listing.price %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

        </div><!-- .tab-pane#whishlist -->
      </div><!-- .tab-content -->
    </div><!-- .col-sm-8 -->
  </div><!-- .row -->
</section><!-- .container -->

app/views/offers/new.html.erb
<div class="row">
 <h1>Making an offer for <%= @offer.listing.title %></h1>
	<%= render 'form', offer: @offer %>
</div>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Listing:</strong>
  <%= @offer.listing.title %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @offer.user.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @offer.price %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @offer.stage %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>