config/routes.rb
Rails.application.routes.draw do

  resources :offers do
    member do
      get 'accept'
      get 'decline'
      get 'payment'
      get 'express_checkout'
    end
  end
  resources :login, only: [:index]
  resources :search, only: [:index]
	resources :listings do
    member do
      get 'offer'
      post 'favourite'
      post 'unfavourite'
    end
  end

  get '/brands/featured', to: 'brands#featured'
	resources :brands
  resources :category

	devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => 
    "users/omniauth_callbacks" }
  root to: 'listings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord

		# setup friendly id
		extend FriendlyId
		friendly_id :name, use: :slugged

		has_many :listings

		validates_presence_of :name, :description, :url, :slug
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  before_action :set_wishlist, only: [:show]
  before_action :set_listing_information, only: [:show]
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.order(:name)
  end

  def featured
    @brands = Brand.limit(32)

    respond_to do |format|
      format.html { render :template => "brands/featured" }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @categories = Category.order(:name)
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
			@brand = Brand.friendly.find(params[:id])
    end

    def set_wishlist
      if user_signed_in?
        @wishlists = current_user.wishlists.pluck(:listing_id)
      else
        @wishlists = []
      end
    end

    def set_listing_information
      @maximum_price = Listing.maximum(:price)
      @minimum_price = Listing.minimum(:price)

      @listings = @brand.listings.filter(params.slice(:category, :colour))
        .order(created_at: :desc)
        .paginate(:page => params[:page], :per_page => 32)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
				params.fetch(:brand).permit(:name, :description, :url)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :brand_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :brand_description %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :brand_url %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/featured.html.erb
<p id="notice"><%= notice %></p>


<section class="container-fluid padding-top-3x">
  <h1 class="space-top-half tablet-center">Featured Designers <%= link_to "View All Designers", brands_path, class: 'btn btn-success pull-right' %></h1>
</section>

<section class="container-fluid padding-bottom-3x">
<div class='row'>
  <%= render 'brands/partials/brands_container' %>
</div>
</section>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>


<section class="container-fluid padding-top-3x">
  <h1 class="space-top-half tablet-center">All Designers</h1>
</section>

<section class="container-fluid padding-bottom-3x">
<div class='row'>
  <%= render 'brands/partials/brands_list_container' %>
</div>
</section>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<section class="container-fluid padding-top-3x">
				<h1 class="space-top-half tablet-center"><%= @brand.name %></h1>
</section>

<%= render 'listings/partials/filters_and_listings' %>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>